#!/usr/bin/env python3
"""
Customizer field inventory generator.

Parses every Field::add() call in:
  inc/Customizer_Settings/Fields/*.php
  inc/compatibility/*/*.php

and emits a snapshot listing type, setting id, section, and default for each.
Run from the theme root and redirect to docs/customizer-inventory-snapshot.txt:

    python3 tools/dump-customizer-inventory.py > docs/customizer-inventory-snapshot.txt

The snapshot is committed to the repo so any field drift (adds, removes,
type changes, default changes) shows up in pull-request diffs. CI can use
the same script to detect undocumented changes.

This parser does not run WP — it reads PHP source files only. No DB access,
no plugins required.
"""
import os
import re
import sys
import glob
from collections import defaultdict


def parse_field_block(lines, start_idx):
    """Read from `Field::add( 'type',` through to the matching `);`.

    Returns (block_text, end_idx). Tracks paren depth across newlines so
    nested arrays don't fool the scanner.
    """
    depth = 0
    started = False
    j = start_idx
    block = []
    while j < len(lines):
        ln = lines[j]
        for ch in ln:
            if ch == '(':
                depth += 1
                started = True
            elif ch == ')':
                depth -= 1
                if started and depth == 0:
                    break
        block.append(ln)
        if started and depth == 0:
            break
        j += 1
    return '\n'.join(block), j


def extract_default(body):
    """Find the value passed to 'default' => …. Returns a printable string."""
    m = re.search(r"'default'\s*=>\s*", body)
    if not m:
        return '(none)'
    tail = body[m.end():]
    if tail.startswith('array('):
        return '<array>'
    m_str = re.match(r"'((?:[^'\\]|\\.)*)'", tail)
    if m_str:
        return repr(m_str.group(1))
    m_bool = re.match(r"(true|false)", tail)
    if m_bool:
        return m_bool.group(1)
    m_num = re.match(r"(-?\d+(?:\.\d+)?)", tail)
    if m_num:
        return m_num.group(1)
    return '(complex)'


def scan(theme_root):
    files = sorted(
        glob.glob(os.path.join(theme_root, 'inc/Customizer_Settings/Fields/*.php'))
        + glob.glob(os.path.join(theme_root, 'inc/compatibility/*/*.php'))
    )
    type_re = re.compile(r"Field::add\(\s*'([a-z_-]+)'\s*,")
    records = []
    for f in files:
        with open(f) as fp:
            lines = fp.read().split('\n')
        i = 0
        while i < len(lines):
            m = type_re.search(lines[i])
            if not m:
                i += 1
                continue
            ftype = m.group(1)
            body, end_idx = parse_field_block(lines, i)
            sid = re.search(r"'settings'\s*=>\s*'([^']+)'", body)
            sec = re.search(r"'section'\s*=>\s*'([^']+)'", body)
            if sid and sec:
                records.append({
                    'type': ftype,
                    'setting': sid.group(1),
                    'section': sec.group(1),
                    'default': extract_default(body),
                    'file': os.path.basename(f),
                })
            i = end_idx + 1
    return records


def render(records):
    by_section = defaultdict(list)
    for r in records:
        by_section[r['section']].append(r)

    out = []
    out.append("# BuddyX Customizer Field Inventory Snapshot")
    out.append("")
    out.append(f"Generated by tools/dump-customizer-inventory.py")
    out.append(f"Source: inc/Customizer_Settings/Fields/*.php + inc/compatibility/*/*.php")
    out.append(f"Total fields: {len(records)} across {len(by_section)} sections")
    out.append("")
    out.append("This snapshot is committed to git so any drift in field declarations")
    out.append("(adds, removes, type changes, default changes) shows up in pull-request diffs.")
    out.append("Regenerate with `python3 tools/dump-customizer-inventory.py > docs/customizer-inventory-snapshot.txt`")
    out.append("")
    out.append("=" * 95)
    out.append(f"{'#':>4} | {'TYPE':16} | {'SETTING':40} | {'DEFAULT':22} | FILE")
    out.append("-" * 95)
    n = 0
    for section in sorted(by_section):
        rows = sorted(by_section[section], key=lambda r: r['setting'])
        out.append("")
        out.append(f"[{section}]  ({len(rows)} fields)")
        for r in rows:
            n += 1
            d = r['default']
            d = (d[:20] + '..') if len(d) > 22 else d
            out.append(f"{n:>4} | {r['type']:16} | {r['setting']:40} | {d:22} | {r['file']}")
    out.append("")
    out.append(f"TOTAL: {n} fields")
    return '\n'.join(out)


def main():
    theme_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    records = scan(theme_root)
    print(render(records))


if __name__ == '__main__':
    main()
